version: "3"
services:
    ktimezmob:
        image: nginx:latest
        ports:
            - 9090:80
        networks:
            - mobilenet
        depends_on:
            - php
            - redis
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - ".:/var/www/html"
        deploy:
            restart_policy:
                condition: on-failure
    php:
        image: nanoninja/php-fpm
        networks:
            - mobilenet
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ".:/var/www/html"
        deploy:
            restart_policy:
                condition: on-failure
    redis:
        image: redis:latest
        ports:
            - "6379"
        volumes:
            - redis-data:/data
        networks:
            - mobile
        deploy:
            restart_policy:
                condition: on-failure
networks:
    mobilenet:
volumes:
    redis-data:
        driver: local

